name: CD - Continuous Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Simulação de Deploy
      run: |
        echo "Iniciando o processo de Continuous Deployment..."
        echo "Validando artefatos da aplicação..."
        echo "Deploy concluído com sucesso no ambiente de produção!"