name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm ci

    - name: Executar testes automatizados
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Simulação de Deploy
      run: echo "Deploy concluído com sucesso no ambiente de produção!!"